public class Main {

    public static void main(String[] args) {

        String[] testData = {
                "Harley-Davidson",
                "Honda",
                "Yamaha",
                "Kawasaki",
                "Suzuki",
                "Ducati",
                "BMW Motorrad",
                "KTM",
                "Triumph",
                "Aprilia",
                "Moto Guzzi",
                "Indian Motorcycle",
                "Royal Enfield",
                "MV Agusta",
                "Benelli",
                "Husqvarna",
                "GasGas",
                "Zero Motorcycles",
                "CFMoto",
                "Bajaj",
                "Hero MotoCorp",
                "TVS Motor",
                "Mahindra Two Wheelers",
                "Lifan",
                "Zontes",
                "Keeway",
                "Kymco",
                "SYM",
                "Vespa",
                "Piaggio",
                "Norton",
                "Bimota",
                "Beta Motor",
                "Sherco",
                "Ural",
                "Victory Motorcycles",
                "Energica",
                "Lightning Motorcycle",
                "Alta Motors",
                "Hyosung",
                "Daelim",
                "Rieju",
                "Mondial",
                "Fantic",
                "SWM",
                "Can-Am",
                "Sachs",
                "Derbi",
                "AJP",
                "Cleveland CycleWerks",
                "Moto Morini",
                "Voge",
                "QJMotor",
                "Haojue",
                "Loncin",
                "Skyteam",
                "Mash Motors",
                "Buell",
                "Arc Motorcycle",
                "Super Soco",
                "Horwin",
                "NIU",
                "Yadea",
                "Sinnis",
                "Lambretta",
                "Brough Superior",
                "Boss Hoss",
                "Big Dog Motorcycles",
                "Confederate Motorcycles",
                "CCM Motorcycles",
                "Herald Motor Co",
                "Macbor",
                "FB Mondial",
                "Zündapp",
                "Jawa",
                "CZ",
                "Ather Energy",
                "Ola Electric",
                "Evoke Motorcycles",
                "Tacita",
                "Brutus Motorcycle",
                "Motus Motorcycles",
                "Ecosse Moto Works",
                "Midual",
                "Janus Motorcycles",
                "SSR Motorsports",
                "Rokon",
                "American IronHorse",
                "Yamaha Star",
                "Kawasaki Ninja",
                "Honda Gold Wing",
                "Suzuki Hayabusa",
                "Ducati Panigale",
                "BMW GS",
                "Triumph Bonneville",
                "KTM Duke",
                "Aprilia RSV4",
                "Royal Enfield Bullet"
        };

        StringArray names = new StringArray(testData);

        System.out.println(names.toString());
        names.append("Monke");
        System.out.println(names.toString());
        names.insert(4,"DERBI");
        System.out.println(names.toString());
        names.reverse();
        System.out.println(names.toString());

        new BigO();
    }
}
